sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sitcomtn-003
env:
  global:
    -
      # LTD_AWS_ID
      secure: B44+KE1xhNz+8mthEtPrHom8dQHGQzb48vixRQyX/usoTMkPhXyhOK9pyvCwWaWaf4VuauJDiVPj4l1WH1lbONhH/o5oyBdY9PxJ6qujT35souBiviK/+btW0mkOXsqNFqz3cJifUKJCzexW/rmpK+PvnyFiQ6YMnzZToSUmP231jglxL0zCTHEyb/oJgU0IA46Wo4zlmYMoZeP0lwWtajSXOL1ZcOyD091oP5pg3rDAMa1nHN6XHQwx+T57AUhZFjy0rycPlDCZZ3xNvLIEed/gQzzQtce5TrGzn4U0WqP1QjvQAIpzHMvsD9svq+f8GDYfRoHCKKteflxx+NW2tefEK5WdlsGYQpI4KRs0Dl0E26Eu2DA63XSy+O611+HwUgKVNjM9zZP6smTKjpLzZ8+nGp9N9hRtQ9mUbQwRwcTartJjE9+lwiI/vg1WCklSYP0iS5Qzhdfr9gKlKcMO2URmtSOXNQAizt+8Uqy8nVfkzraMytsThftU3apQYRrvHMO2Xp7mNpyjg7+KDCeweyJLDBJHc7ronq+sC5tsn6TTghTAk5HKBL+Ffnib5KPe+LPcl6Npbx12BqUlsRdQ6qv0gGgZ1129pObEvQ17OwrFedJyp1YWoxEnWMsHJ4z0T0bxmfFRl2hC/zhkCfANAFyhmO3wI3NodQjf87YFFZg=
    -
      # LTD_AWS_SECRET
      secure: Iq3LaNPUDDV/Kcf4wkLzcEkB1cTWOiRnYQ0jUoiBi/wCO/bimNL6vWhxF9zg21pVhREuAfWvsEQ4ggZJxzuFh9/ECG+7DuZarvlbnopSfAoCuxY0ySGN8HEl3usc6YcL/JZCI14PUsqSgR0xdalKfak3OKE9WBmAkgbBuhA9HmSfXsImAVTSQfPnWeLotuH67//HG73GBGmfoMkGiF1l/kN34xvWgkrVzCEL2ulcRUOvpotDhwo6hSx1mEsMMuargjnxBy+i3GCjKdmuZK7GvoHv6n5YbtL8FQG0bfQj971RVkEVEguJTUZGdATY5jE0xyEs3bTqTYv4Rog+5QQhguHuMdEtfM2SfycYBcGMijYiaSqZ1FLyPVIEKr7Mcrsaeuh91siYhlkoirwMUSzmra/i2SYWcD9Tej9RmxATU1u5XchmyQ9OHPIJE1LloOL8ClAf3h9cxMiS6gNlH3X5PuTej4OABkS81ZDfzkQg7+J26PgjjURJZyhy+kaxEpYQG8Ycw0eMoQFkbZ521GMHM6y40JGv+FoUehkOKTXRZgC3r4vADX1XJwawNev9rdQDEUAluOKvubJgN7wB0RvS/HchbfMosNmZYfLlSGGP8GMkKhNr7Oe8iWBN+lD6wviJyewcS6z96dmHwKKYLIrIGfUg3TpSzCAC8CPpQS5kF8k=
    -
      # LTD_USERNAME
      secure: W98rqdH+xFfbSOybgTE680sWNeyihUMC75mHV67lIXg3IwQiiCu1aHO9MxlnKn7jtYS8P8KSVZTcHcJeDuw+de1MaQxytOb0318EQKBDrfOtQVwWRl8X8mrHgMXuWFKeYtZvOAX5Q6bqPoQrT74IIhJR82H+1K4KQ3kgqPAdv8li4RmGE9aEttS6foDoCzh3WaxZ7qLhTEaqLgHFZWVeBDPktlhNbalP5uokgQjt06Zhc4PwWSpxYHr7giYYwgfAUqP+t/mahLCgFHMViZ8tmfHyporVnHhjtw6NQNRclwdWXx08cheqbNntmZp4zX8rkg0enx2GP65c80XjivBoWDNvpott0wE+Fpul9WzTnApcYRdvPZ9/bUi65nBRSzrv/GUJ4pjACqXn8sgmiCsJnOOQ8X+GSCMPpOPm1y5NNs1FsLb1wtFNvKM4hZ3VjpN5stp29xn925BatTcbftcCrpSgPSYTRWyB+byYx69hUBLDrFa0bGzfSW/OFYxxpw/OxHBbfr1Vn9DDt/l66iNNRAOf4PYnKU0T3cSIMiIK/c6ByMmzxPyJYzyk2SUYHLOp8Nw1zUnyZpDb0eCxOIhaPB9Gx/t5yN/ZCVE/GpTXog3iVuXygZUVgKm45T0SY98BRZgrb09g8TcbRUUIk3Q0uxxa+cVfwH1+V/2J+7IHFbc=
    -
      # LTD_PASSWORD
      secure: enivsaJNfKN9g2Ti0OsZd8oxOobUy1gXFbwVPmPBHm4zIf+tWEQeEGltxRuURBdcDi5GbmViGGQZdi7n4b+7nQ/0L8fGC0W58XExAl6agXgyiaiMHg8Dy5f0YSPn5Rhgc5iBoPI+q9GVekJAvJB9yWDsL+AyYjcC/vH+j4xbLrU9TRK4CE6HvbP0oeQ7ThaKG2MKfqyeBtxoCaIzWPZmVkuhqihqw6eZehvAP0PnWTtVpwBzq8SnmgnKJeqjk5H0FvMlECtqESH1BK9sFGeZaCmG8nvqtyAfis2Ff8JaQgfv6/89iE312o90D3PJpcoAHiRX6Ro5oQaxXI0mPLKeuaX3oSDorlibl10pK3PpvijBp+kP6VNmyzgGJ9qw0DbOORDrljW8qBAbnxi/QKD9D4Utc0DtVZMI/Z879BKF1U+bIZFwbCFA40vL5j5YY/nEVtTa1ADcvsJlxAIWUBzvACgy13k5kKR6k0U0qu+bdDNKQktBDKgst/HluR5D/DtEsdN/9MSC1C44XUNmaV2qNfwF4xmZ5PcDAyeMw5U5Uz/cm5VBGmff6Qqmnny8V0Xc6KZ891ROHqxwjLaptJmtRsFL4YPdNLcB/vkhJFqMi7AsL70I9/pKGfrGbprf+6T1nBDpKM1CUceuoG3RgznRg721ni+AuTSsRsqmb1O4Rx4=
